### ISSUE TITLE
npm warnings and legacy demand

### ISSUE THREAD

**Issue by ppKrauss** [mjhea0/node-postgres-todo#7]
Using basic and fresh UBUNTU 16... 
```sh
git clone https://github.com/mjhea0/node-postgres-todo.git
cd node-postgres-todo
npm install
 npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the 
          latest version of pug instead of jade
 npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
```

After `psql -h localhost -U postgres` and `CREATE DATABASE todo`, run

```sh
node server/models/database.js
  The program 'node' is currently not installed. You can install it by typing:
     apt install nodejs-legacy
```

But I not like to polute system to legacy, etc..  **There are a way to avoid warnings and the legacy demand?**

**Comment by ppKrauss** [comment]
Using [this considerations](http://stackoverflow.com/a/40202458/287948) I run `node`,

```sh
node server/models/database.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

error: password authentication failed for user "root"
    at Connection.parseE (/root/sanbox/node-postgres-todo/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/root/sanbox/node-postgres-todo/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/root/sanbox/node-postgres-todo/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by ppKrauss** [comment]
ops

**Comment by mjhea0** [comment]
@ppKrauss Is this still an issue?

**Comment by ppKrauss** [comment]
Hi @mjhea0 , yes... there are something wrong with password, or other env. error.

**Comment by mjhea0** [comment]
You have a username and password on your database. You need to add it to the connection string. For example:

```
var connectionString = process.env.DATABASE_URL || 'postgresql://ADD-USERNAME:ADD-PASSWORD@localhost:5432/todo';
```

**Comment by ppKrauss** [comment]
Thanks @mjhea0 (!). Please a "explanation for dummies", where I change the code?  The filename or all shell comands, step-by-step.

**Comment by mjhea0** [comment]
You need to update the connection string here -> https://github.com/mjhea0/node-postgres-todo/blob/master/server/models/database.js#L2

**Comment by ppKrauss** [comment]
Thanks @mjhea0 (!), now databese script worked, `node server/models/database.js` ok!

But, the next command fails,

```
npm start

> node-postgres-todo@0.0.0 start /root2/sanbox/node-postgres-todo
> supervisor ./bin/www

sh: 1: supervisor: not found

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! node-postgres-todo@0.0.0 start: `supervisor ./bin/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-postgres-todo@0.0.0 start script 'supervisor ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-postgres-todo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     supervisor ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-postgres-todo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-postgres-todo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root2/sanbox/node-postgres-todo/npm-debug.log
```

**Comment by mjhea0** [comment]
looks like you need to install [supervisor](https://github.com/petruisfan/node-supervisor):

```
npm install supervisor -g
```

**Comment by ppKrauss** [comment]
Thanks again @mjhea0!  Hum... it is running, but I am using the same port, where I can change it?

-----

```
Starting child process with 'node ./bin/www'
Port 3000 is already in use
Program node ./bin/www exited with code 1
```

**Comment by mjhea0** [comment]
https://github.com/mjhea0/node-postgres-todo/blob/master/bin/www#L15

**Comment by ppKrauss** [comment]
Thanks! I changed to 3010, and try `curl http://127.0.0.1:3010/api/v1/todos`, 
```json
{"success":false,
 "data":{
  "name":"error",
  "length":93,
  "severity":"FATAL",
  "code":"28P01","file":"auth.c","line":"288","routine":"auth_failed"
  }
}
```

How to run basic tests, I need other authorization? 

PS: also testing  `npm start` after `su - postgres`,  not work.
